scene_name: 'abandoned_house'
near: 0.1
far: 615
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0 ]
x_range : [-250, 175]
y_range : [2, 150]
z_range : [-200, 200]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [100, 150] # used for scaling random
#scale_unit: 20 # height 3m
scale_unit: 17.3

#over all min [-252.354202, -2.8e-05, -210.182541]
#over all max [177.958298, 165.062515, 198.380035]

object_labels:
  Material2.004_cable: 
    label: 'ceiling'
  Material2.001:
    label: 'wall'
  Material2.002:
    label: 'window'
  Material2.003:
    label: 'floor'
  Material2.005:
    label: 'window'
  Material3:
    label: 'objects'
  Material3.001:
    label: 'wall'