scene_name: 'abandoned_house'
near: 0.1
far: 615
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0 ]
x_range : [-250, 175]
y_range : [2, 150]
z_range : [-200, 200]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [100, 150] # used for scaling random