scene_name: 'bathroom6_layout'
near: 0.1
far: 13
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-2.0, 4.2]
y_range : [0.3, 4.2]
z_range : [-3.1, 5.4]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-2.771046, -1e-06, -3.320153]
#Max [4.447175, 4.574996, 5.604837]

object_labels:
  mirror.1234:
    label: 'objects'
  wall.023:
    label: 'wall'
  light.043:
    label: 'objects'
  ceiling.1000:
    label: 'ceiling'
  window_frame.012:
    label: 'window'
  wall.024:
    label: 'wall'
  window.011:
    label: 'window'
  bench:
    label: 'furniture'
  light.041:
    label: 'objects'
  light.045:
    label: 'objects'
  wall.00111:
    label: 'wall'
  wall.025:
    label: 'wall'
  floor.011:
    label: 'floor'
  floor.010:
    label: 'floor'
  wall.026:
    label: 'wall'
  floor.012:
    label: 'floor'
  light.046:
    label: 'objects'
  light.044:
    label: 'objects'
  toilet_paper.001:
    label: 'objects'
  light.042:
    label: 'objects'
  mirror.011:
    label: 'objects'