scene_name: 'bathroom6_layout'
near: 0.1
far: 13
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-2.0, 4.2]
y_range : [0.3, 4.2]
z_range : [-3.1, 5.4]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-2.771046, -1e-06, -3.320153]
#Max [4.447175, 4.574996, 5.604837]






