scene_name: 'bathroom3_layout'
near: 0.1
far: 6
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-3, 1.5]
y_range : [0, 2.6]
z_range : [-0.6, 1.2]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-3.069814, 0.0, -0.952551]
#Max [1.764898, 2.799998, 1.330898]

object_labels:
  shower.12001:
    label: 'objects'
  light.011:
    label: 'objects'
  mirror.004:
    label: 'objects'
  wall.005:
    label: 'wall'
  floor.002:
    label: 'floor'
  mirror.003:
    label: 'objects'
  ceiling.002:
    label: 'ceiling'
  light.010:
    label: 'objects'
  light.009:
    label: 'objects'
  blinds.001:
    label: 'window'
  window.002:
    label: 'window'
  light.008:
    label: 'objects'
  decoration.005:
    label: 'objects'
  decoration.008:
    label: 'objects'

