scene_name: 'bathroom1_layout'
near: 0.1
far: 15
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-0.7, 0.7]
y_range : [0.1, 3.4]
z_range : [-1.7, 1.3]
yaw_range : [-40, 40]
pitch_range: [-40, 40]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-0.802209, 0.0, -1.755469]
#Max [0.751443, 3.500003, 1.324533]

