scene_name: 'bathroom3_layout'
near: 0.1
far: 6
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-3, 1.5]
y_range : [0, 2.6]
z_range : [-0.6, 1.2]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-3.069814, 0.0, -0.952551]
#Max [1.764898, 2.799998, 1.330898]



