scene_name: 'bedroom2_layout'
near: 0.1
far: 13
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-3.5, 2.3]
y_range : [0.1, 3.2]
z_range : [-5.2, 4.5]
scale_range: [1, 2] # used for scaling random
#scale_unit: 1000
scale_unit: 885
#Min [-3.8633, -0.102001, -5.403452]
#Max [2.481103, 3.325202, 4.867952]

object_labels:
  blinds:
    label: 'window'
  book:
    label: 'books'
  book.001:
    label: 'books'
  book.002:
    label: 'books'
  book.003:
    label: 'books'
  book.004:
    label: 'books'
  book.005:
    label: 'books'
  carafe:
    label: 'objects'
  ceiling.001:
    label: 'ceiling'
  curtain.001:
    label: 'window'
  floor.001:
    label: 'floor'
  lamp.005:
    label: 'objects'
  light.001:
    label: 'objects'
  mirror:
    label: 'objects'
  painting.001:
    label: 'picture'
  television:
    label: 'tv'
  shelf:
    label: 'furniture'
  vase:
    label: 'objects'
  wall.001:
    label: 'wall'
  window.001:
    label: 'window'
  
