scene_name: 'bedroom5_layout'
near: 0.1
far: 10
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-3.1, 3.1]
y_range : [0.1, 2.5]
z_range : [-2.3, 2.2]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-3.364396, -0.038755, -2.494939]
#Max [3.395598, 2.781243, 2.36506]

object_labels:
  ceiling.003:
    label: 'ceiling'
  curtain:
    label: 'window'
  curtain.003:
    label: 'window'
  curtain.004:
    label: 'window'
  chandelier:
    label: 'objects'  
  door.003:
    label: 'wall'
  door.004:
    label: 'wall'
  doorframe:
    label: 'wall'
  doorframe.001:
    label: 'wall'
  floor.003:
    label: 'floor'
  light:
    label: 'objects'
  light.001:
    label: 'objects'
  mat:
    label: 'objects'
  mirror.001:
    label: 'objects'
  mirror.002:
    label: 'objects'
  wall.004:
    label: 'wall'
  wall.005:
    label: 'wall'
  wall.006:
    label: 'wall'
  wall.007:
    label: 'wall'
  wardrobe:
    label: 'furniture'
  window:
    label: 'window'
  windows:
    label: 'window'
  window.001:
    label: 'window'
  window.004:
    label: 'window'
  windowsill:
    label: 'furniture'
