scene_name: 'bedroom4_layout'
near: 0.1
far: 8
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-1.6, 3.7]
y_range : [0.1, 2.5]
z_range : [-2.9, 0.0]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-1.764323, -0.05, -3.186911]
#Max [3.969727, 2.700776, 0.283762]


object_labels:
  Ceiling:
    label: 'ceiling'
  painting.006:
    label: 'picture'
  television.001:
    label: 'tv'
  light:
    label: 'objects'
  Wall:
    label: 'wall'
  wall.003:
    label: 'wall'
  Floor:
    label: 'floor'
  Door:
    label: 'wall'
  Door.001:
    label: 'wall'
  cupboard:
    label: 'furniture'
  Carpet:
    label: 'objects'
  air_conditioner.002:
    label: 'furniture'