scene_name: 'bedroom'
near: 0.1
far: 6
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0 ]
x_range : [-2.5, 2.5]
y_range : [0.1, 1.6]
z_range : [-1.5, 1.5]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [0.8, 1.5] # used for scaling random
scale_unit: 1600

#over all min [-2.700973, -0.090563, -1.574304]
#over all max [2.713026, 1.759939, 1.780447]
