scene_name: 'classroom_1'
near: 0.1
far: 27
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0, 0, 0]
center_translation_vec: [ 0,  0,  0]
x_range : [-11, 11]
y_range : [0.05, 7]
z_range : [-8, 8]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [3, 6] # used for scaling random
scale_unit: 400
#over all min [-12.476286, -0.030705, -8.710097]
#over all max [12.088182, 7.134542, 8.355046]
