scene_name: 'classroom_3'
near: 0.1
far: 27
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0, 0, -10]
center_translation_vec: [ 0,  0,  0]
x_range : [-10, 10]
y_range : [0.05, 6]
z_range : [-9, 9]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [2, 5] # used for scaling random