scene_name: 'classroom'
near: 0.1
far: 100000
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0, 0, 0]
center_translation_vec: [0, 0, 0]
x_range : [-11, 11]
y_range : [-0.25, 7.25]
z_range : [-8, 8]
yaw_range : [0, 360]
pitch_range: [0, 360]