scene_name: 'dumbledore'
near: 0.001
far: 0.17
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0, 0, 0]
center_translation_vec: [  0,   0, 0]
x_range : [-0.03, 0.03]
y_range : [-0.003, 0.03]
z_range : [-0.02, 0.02]
yaw_range : [0, 90]
pitch_range: [0, 90]
scale_range: [0.01, 0.03] # used for scaling random
scale_unit: 50000

#over all min [-0.059991, -0.0075, -0.042725]
#over all max [0.084298, 0.124208, 0.042725]