scene_name: 'empty_house'
near: 0.1
far: 575
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0 ]
#x_range : [-250, 0]
x_range : [-200, 190]
y_range : [1, 200]
z_range : [-400, 40]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [100, 150] # used for scaling random
scale_unit: 15
#over all min [-318.6875, -5.5e-05, -410.875153]
#over all max [476.0625, 281.5, 150.812515]

object_labels:
  Material2:
    label: 'objects'
  Material2.001:
    label: 'ceiling'
  Material2.002:
    label: 'window'
  Material2.003:
    label: 'window'
  Material2.004:
    label: 'wall'
  Material2.005:    
    label: 'wall'
  Material2.006:
    label: 'wall'
  Material2.007:  
    label: 'floor'
  Material2.008:
    label: 'objects'
  Material3:
    label: 'objects' # check lại
  Material3.001:  
    label: 'objects' # check lại