scene_name: 'kitchen3_layout'
near: 0.1
far: 12
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-1.9, 5.2]
y_range : [-0.1, 3.1]
z_range : [0.6, 6.0]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-2.15514, -0.300001, 0.80606]
#Max [5.433269, 3.340001, 6.253724]

object_labels:
  carpet.005:
    label: 'objects'
  ceiling.020:
    label: 'ceiling'
  floor.013:
    label: 'floor'
  light:
    label: 'objects'
  light.001:
    label: 'objects'
  wall.044:
    label: 'wall'
  window.032:
    label: 'window'