scene_name: 'kitchen2_layout'
near: 0.1
far: 7
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-2.4, 1.0]
y_range : [0.1, 2.8]
z_range : [-0.5, 4.1]
scale_range: [1, 2] # used for scaling random
scale_unit: 1000
#Min [-2.604978, -0.121956, -0.720811]
#Max [1.25335, 2.999998, 4.359737]
# not good scene
object_labels:
  door:
    label: 'objects'
  wall.041:
    label: 'wall'
  wall.042:
    label: 'wall'
  wall.043:
    label: 'wall'
  window.031:
    label: 'window'