scene_name: 'livingroom2_layout'
near: 0.1
far: 18
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-8.5, 7.7]
y_range : [0.1, 2.6]
z_range : [-1.6, 2.5]
yaw_range : [-40, 40]
pitch_range: [-40, 40]
scale_range: [1, 2] # used for scaling random
#scale_unit: 1000
scale_unit: 550
#Min [-8.787218, -1e-06, -1.783522]
#Max [7.925558, 2.850473, 2.679925]

object_labels:
  blinds.100:
    label: 'window'
  carpet:
    label: 'objects'
  ceiling:
    label: 'ceiling'
  ceiling.001:
    label: 'ceiling'
  ceiling.002:
    label: 'ceiling'
  ceiling.003:
    label: 'ceiling'
  ceiling.004:
    label: 'ceiling'
  ceiling.005:
    label: 'ceiling'
  ceiling.006:
    label: 'ceiling'
  ceiling.007:
    label: 'ceiling'
  ceiling.008:
    label: 'ceiling'
  ceiling.009:
    label: 'ceiling'
  curtains:
    label: 'window'
  decoration.111:
    label: 'objects'
  decoration.1001:
    label: 'objects'
  door:
    label: 'wall'
  door.002:
    label: 'wall'
  door.003:
    label: 'wall'
  door.004:
    label: 'wall'
  door.005:
    label: 'wall'
  door.006: 
    label: 'wall'
  drawer.100:
    label: 'furniture'
  drawer.001:
    label: 'furniture'
  faucet.001:
    label: 'objects'
  floor:
    label: 'floor'
  floor.002:
    label: 'floor'
  furniture:
    label: 'furniture'
  glasses:
    label: 'objects'
  lamp.001:
    label: 'objects'
  light.119:
    label: 'objects'
  lightbulb.100:
    label: 'objects'
  painting:
    label: 'painting'
  painting.100:
    label: 'painting'
  shelf:
    label: 'furniture'
  speakers:
    label: 'objects'
  television:
    label: 'tv'
  wall.001:
    label: 'wall'
  wall.002:
    label: 'wall'
  wall.003:
    label: 'wall'
  wall.004:
    label: 'wall'
  wall.005:
    label: 'wall'
  wall.006:
    label: 'wall'
  wall.007:
    label: 'wall'
  wall.008:
    label: 'wall'
  wall.009:
    label: 'wall'
  wall.010:
    label: 'wall'
  wall.012:
    label: 'wall'
  windows:
    label: 'window'
  windows.001:
    label: 'window'
  