scene_name: 'living_room_2'
near: 0.1
far: 19
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0]
x_range : [-7, 3]
y_range : [0, 6]
z_range : [-9, 5]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [2, 4] # used for scaling random
scale_unit: 500

#Min [-7.323953, -0.02368, -9.553816]
#Max [3.43398, 6.305682, 5.758204]

