scene_name: 'livingroom4_layout'
near: 0.1
far: 14
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-4.5, 4.8]
y_range : [0.1, 3.0]
z_range : [-2.9, 4.5]
scale_range: [1, 2] # used for scaling random
#scale_unit: 1000
scale_unit: 900

#Min [-4.715546, -0.001144, -3.186525]
#Max [5.01329, 3.266924, 4.749554]
