scene_name: 'living_room'
near: 0.1
far: 17
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0]
x_range : [-2, 9]
y_range : [0.2, 4]
z_range : [-5, 5]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [1.5, 3] # used for scaling random