scene_name: 'living_room'
near: 0.1
far: 17
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
cameraPos: [0.0, 0.0, -10.0]
center_translation_vec: [ 0, 0, 0]
x_range : [-2, 9]
y_range : [0.2, 4]
z_range : [-5, 5]
yaw_range : [0, 360]
pitch_range: [0, 360]
scale_range: [1.5, 3] # used for scaling random
#scale_unit: 750
scale_unit: 630
#over all min [-2.900853, -0.000301, -5.389286]
#over all max [9.265402, 4.011915, 5.244027]

object_labels:
  carpet:
    label: 'objects'
  curtain:
    label: 'window'
  dec:
    label: 'objects'
  floor:
    label: 'floor'
  house:
    label: 'wall'
  lamp:
    label: 'objects'
  light:
    label: 'objects'
  pillow:
    label: 'objects'
  plants:
    label: 'objects'
  Plastic_pot:
    label: 'objects'
  sofa:
    label: 'sofa'
  table:
    label: 'table'
  vase:
    label: 'objects'
  wall:
    label: 'wall'