scene_name: 'office3_layout'
near: 0.1
far: 19
cameraPos: [0.0, 0.0, 0]
center_translation_vec: [ 0, 0, 0]
x_range : [-6.4, 6.1]
y_range : [0.1, 3.3]
z_range : [-5.4, 7.0]
scale_range: [1, 2] # used for scaling random
#scale_unit: 1000
scale_unit: 680
#Min [-6.607386, -0.008232, -5.66283]
#Max [6.303257, 3.411776, 7.24781]

