scene_name: 'warehouse'
near: 0.1
far: 15
sphere_radius: 2
view_range: [0, 360] # angle view
#cameraPos: [0.0, 0.6, 3.3]
#cameraPos: [0.0, 0.0, -10]
cameraPos: [0.0, 0.0, 0.0]
#center_translation_vec: [ 0,  -0.5,  1.6]
center_translation_vec: [ 0,  0,  0]
x_range : [-3.7, 5]
y_range : [-0.8, 0.7]
z_range : [-3.2, -0.2]
yaw_range : [0, 360]
scale_range: [1, 2] # used for scaling random
scale_unit: 3000 # height 4.5m
pitch_range: [0, 360]
#over all min [-4.059946, -0.853369, -3.678474]
#over all max [5.551205, 1.070903, 0.163488]
